// graphviz.ts
import { Connector } from "./connector";
import { Cable } from "./cable";
import { Pin } from "./pin";
import fs from 'node:fs';
import { DiagramError } from "./errors";

/**
 * Generates a Graphviz representation of a wiring diagram
 * @param connectors - Array of connector objects to be included in the diagram
 * @param cables - Array of cable objects to be included in the diagram
 * @returns String containing Graphviz DOT language representation of the wiring diagram
 * @throws {DiagramError} If diagram generation fails
 */
export function generateGraphviz(connectors: Connector[], cables: Cable[]): string {
  try {
    // Validate inputs
    if (!connectors || !Array.isArray(connectors) || connectors.length === 0) {
      throw new DiagramError("No connectors provided for diagram generation");
    }
    
    if (!cables || !Array.isArray(cables) || cables.length === 0) {
      throw new DiagramError("No cables provided for diagram generation");
    }
    
    // Determine connector placement (left vs right)
    const { leftConnectors, rightConnectors } = determineConnectorPlacement(cables);

    // Generate all diagram components
    const connectorNodes = generateConnectorNodes(connectors, leftConnectors);
    const cableNodes = generateCableNodes(cables);
    const edges = generateEdges(cables, connectors);

    // Combine everything into the final Graphviz output
    return `
      graph {
        // Graph generated by https://typeCAD.net
        // Graphviz look heavily influenced by https://github.com/wireviz/WireViz
        graph [bgcolor="#FFFFFF" fontname=arial nodesep=0.33 rankdir=LR ranksep=2]
        node [fillcolor="#FFFFFF" fontname=arial height=0 margin=0 shape=none style=filled width=0]

        // Placement rules
        { rank = same; ${Array.from(leftConnectors).join("; ")} }
        { rank = same; ${cables.map(cable => cable.name).join("; ")} }
        { rank = same; ${Array.from(rightConnectors).join("; ")} }

        ${connectorNodes}
        ${cableNodes}
        ${edges}
      }
    `;
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to generate Graphviz content: ${error.message}`);
    }
  }
}

/**
 * Writes the generated Graphviz output to a file
 * @param connectors - Array of connector objects
 * @param cables - Array of cable objects
 * @param filePath - Path to write the Graphviz DOT file
 * @throws {DiagramError} If the file cannot be written or diagram generation fails
 */
export function writeGraphvizToFile(connectors: Connector[], cables: Cable[], filePath: string): void {
  try {
    // Validate inputs
    if (!connectors || !Array.isArray(connectors)) {
      throw new DiagramError("Invalid connectors array");
    }
    
    if (!cables || !Array.isArray(cables)) {
      throw new DiagramError("Invalid cables array");
    }
    
    if (!filePath) {
      throw new DiagramError("Invalid file path");
    }
    
    // Generate the Graphviz output
    const graphvizOutput = generateGraphviz(connectors, cables);
    
    // Write to file
    try {
      fs.writeFileSync(filePath, graphvizOutput, 'utf8');
      console.log(`Graphviz output successfully written to ${filePath}`);
    } catch (error) {
      throw new DiagramError(`Error writing to file: ${error.message}`, filePath);
    }
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Error generating diagram: ${error.message}`, filePath);
    }
  }
}

// Helper functions for diagram generation follow
// These are not exported as they're only used internally

/**
 * Determines which connectors should be placed on the left vs right side of the diagram
 * based on their connections in cables
 */
function determineConnectorPlacement(cables: Cable[]): { leftConnectors: Set<string>, rightConnectors: Set<string> } {
  try {
    const leftConnectors: Set<string> = new Set();
    const rightConnectors: Set<string> = new Set();
    const allConnectors: Set<string> = new Set();

    // First, collect all connector names
    cables.forEach(cable => {
      cable.nets.forEach(net => {
        net.pins.forEach(pin => {
          if (!pin.owner) {
            throw new DiagramError(`Pin in cable '${cable.name}' has no owner connector`);
          }
          allConnectors.add(pin.owner);
        });
      });
    });

    // If no connectors were found, throw an error
    if (allConnectors.size === 0) {
      throw new DiagramError("No connectors found in cables");
    }

    // Process non-shield nets first to establish the primary layout
    cables.forEach(cable => {
      cable.nets.forEach(net => {
        if (net.isShield) return; // Skip shield nets in this pass
        
        if (net.pins.length > 0) {
          // Add first pin owner to left side if not already on right
          const firstOwner = net.pins[0].owner;
          if (!rightConnectors.has(firstOwner)) {
            leftConnectors.add(firstOwner);
          }
          
          // Add remaining pin owners to right side if not already on left
          for (let i = 1; i < net.pins.length; i++) {
            const owner = net.pins[i].owner;
            if (!leftConnectors.has(owner)) {
              rightConnectors.add(owner);
            }
          }
        }
      });
    });

    // Process shield nets and handle any unassigned connectors
    cables.forEach(cable => {
      cable.nets.forEach(net => {
        if (!net.isShield) return;
        
        if (net.pins.length > 0) {
          for (let i = 0; i < net.pins.length; i++) {
            const owner = net.pins[i].owner;
            if (!leftConnectors.has(owner) && !rightConnectors.has(owner)) {
              rightConnectors.add(owner);
            }
          }
        }
      });
    });

    // Remove any connector that ended up on both sides (prioritize right side)
    leftConnectors.forEach(connector => {
      if (rightConnectors.has(connector)) {
        leftConnectors.delete(connector);
      }
    });

    // Assign any remaining connectors to the right side
    allConnectors.forEach(connector => {
      if (!leftConnectors.has(connector) && !rightConnectors.has(connector)) {
        rightConnectors.add(connector);
      }
    });

    return { leftConnectors, rightConnectors };
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to determine connector placement: ${error.message}`);
    }
  }
}

/**
 * Generates Graphviz nodes for all connectors
 */
function generateConnectorNodes(connectors: Connector[], leftConnectors: Set<string>): string {
  try {
    if (!connectors || !Array.isArray(connectors)) {
      throw new DiagramError("Invalid connectors array");
    }
    
    if (!leftConnectors || !(leftConnectors instanceof Set)) {
      throw new DiagramError("Invalid leftConnectors set");
    }
    
    return connectors
      .map((connector) => generateConnectorNode(connector, leftConnectors.has(connector.name)))
      .join("\n");
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to generate connector nodes: ${error.message}`);
    }
  }
}

/**
 * Generates Graphviz representation of a single connector
 */
function generateConnectorNode(connector: Connector, isLeft: boolean): string {
  try {
    if (!connector || !connector.name) {
      throw new DiagramError("Invalid connector or missing connector name");
    }
    
    const metadataRows = generateConnectorMetadataRows(connector);
    const mpnRow = connector.mpn ? `<tr><td border="1" cellpadding="3" balign="left">${connector.mpn}</td></tr>` : '';
    const pinRows = generateConnectorPinRows(connector, isLeft);
    const additionalsRows = generateAdditionalsRows(connector.additionals);
    const noteRow = generateNoteRow(connector.note);
    const imageRow = generateImageRow(connector.image);

    return `
      ${connector.name} [label=<
        <table border="0" cellspacing="0" cellpadding="0">
          <tr><td>
            <table border="0" cellspacing="0" cellpadding="3" cellborder="1"><tr>
              <td balign="left"><b>${connector.name}</b></td>
            </tr></table>
          </td></tr>
          ${
            metadataRows.length > 0
              ? `<tr><td>
                  <table border="0" cellspacing="0" cellpadding="3" cellborder="1"><tr>
                    ${metadataRows.join("")}
                  </tr></table>
                </td></tr>`
              : ""
          }
          ${mpnRow}
          <tr><td>
            <table border="0" cellspacing="0" cellpadding="3" cellborder="1">
              ${pinRows}
            </table>
          </td></tr>
          ${additionalsRows}
          ${imageRow}
          ${noteRow}
        </table>
      > fillcolor="#FFFFFF" shape=box style=filled]
    `;
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to generate connector node for '${connector?.name || "unknown"}': ${error.message}`);
    }
  }
}

/**
 * Generates metadata rows for a connector (type, subtype, pin count)
 */
function generateConnectorMetadataRows(connector: Connector): string[] {
  const metadataRows: string[] = [];
  
  if (connector.type) {
    metadataRows.push(`<td balign="left">${connector.type}</td>`);
  }
  
  if (connector.subtype) {
    metadataRows.push(`<td balign="left">${connector.subtype}</td>`);
  }
  
  metadataRows.push(`<td balign="left">${connector.pins.length}-pin</td>`);
  
  return metadataRows;
}

/**
 * Generates pin rows for a connector
 * @param connector - Connector object to generate pin rows for
 * @param isLeft - Whether the connector should be placed on the left side
 * @returns String containing HTML table rows for connector pins
 * @throws {DiagramError} If pin rows cannot be generated
 */
function generateConnectorPinRows(connector: Connector, isLeft: boolean): string {
  try {
    if (!connector || !connector.pins || !Array.isArray(connector.pins)) {
      throw new DiagramError(`Invalid pins array for connector ${connector?.name || "unknown"}`);
    }
    
    return connector.pins
      .map((pin: Pin) => {
        if (pin.number === undefined) {
          throw new DiagramError(`Pin missing number in connector ${connector.name}`);
        }
        
        // If the pin has no name or empty name, create a row based on connector side
        if (!pin.name || pin.name === '') {
          if (isLeft) {
            // For left connectors, the pin should be on the right
            // We need to keep the table structure consistent, so add an empty cell on the left
            return `<tr><td port="p${pin.number}">${pin.number}</td></tr>`;
          } else {
            // For right connectors, the pin should be on the left
            // Add an empty cell on the right to maintain structure
            return `<tr><td port="p${pin.number}">${pin.number}</td></tr>`;
          }
        }
        
        // If pin has a name, create both name cell and port cell
        const portCell = `<td port="p${pin.number}">${pin.number}</td>`;
        const nameCell = `<td>${pin.name}</td>`;
        
        // Position them based on connector side
        return `
          <tr>
            ${isLeft ? nameCell : portCell}
            ${isLeft ? portCell : nameCell}
          </tr>
        `;
      })
      .join("");
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to generate pin rows for connector '${connector?.name || "unknown"}': ${error.message}`);
    }
  }
}

/**
 * Generates Graphviz nodes for all cables
 */
function generateCableNodes(cables: Cable[]): string {
  try {
    if (!cables || !Array.isArray(cables)) {
      throw new DiagramError("Invalid cables array");
    }
    
    return cables.map(generateCableNode).join("\n");
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to generate cable nodes: ${error.message}`);
    }
  }
}

/**
 * Generates Graphviz representation of a single cable
 */
function generateCableNode(cable: Cable): string {
  try {
    if (!cable || !cable.name) {
      throw new DiagramError("Invalid cable or missing cable name");
    }
    
    if (!cable.nets || !Array.isArray(cable.nets)) {
      throw new DiagramError(`Invalid nets array for cable ${cable.name}`);
    }
    
    const netRows = generateCableNetRows(cable);
    // Only count regular nets for connection count, not shields
    const connectionCount = cable.nets.filter(net => !net.isShield).length;
    const additionalsRows = generateAdditionalsRows(cable.additionals);
    const noteRow = generateNoteRow(cable.note);
    const imageRow = generateImageRow(cable.image);
    const cableMetadataRow = generateCableMetadataRow(cable, connectionCount);
    
    // Add MPN row for cables, matching connector display
    const mpnRow = cable.mpn ? `<tr><td border="1" cellpadding="3" balign="left">${cable.mpn}</td></tr>` : '';
    
    // Set the style to "dashed" if cable is bundled
    const borderStyle = cable.bundle ? "dashed" : "solid";

    return `
      ${cable.name} [label=<
        <table border="0" cellspacing="0" cellpadding="0">
          <tr><td>
            <table border="0" cellspacing="0" cellpadding="3" cellborder="1"><tr>
              <td balign="left"><b>${cable.name}</b></td>
            </tr></table>
          </td></tr>
          <tr><td>
            <table border="0" cellspacing="0" cellpadding="3" cellborder="1"><tr>
              ${cableMetadataRow}
            </tr></table>
          </td></tr>
          ${mpnRow}
          <tr><td>
            <table border="0" cellspacing="0" cellpadding="0" cellborder="0" width="100%">
              <tr><td colspan="3">&nbsp;</td></tr>
              ${netRows}
              <tr><td colspan="3">&nbsp;</td></tr>
            </table>
          </td></tr>
          ${additionalsRows}
          ${imageRow}
          ${noteRow}
        </table>
      > fillcolor="#FFFFFF" shape=box style=${borderStyle} fillcolor="#FFFFFF"]
    `;
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to generate cable node for '${cable?.name || "unknown"}': ${error.message}`);
    }
  }
}

/**
 * Generates metadata row for a cable
 */
function generateCableMetadataRow(cable: Cable, connectionCount: number): string {
  const cells: string[] = [];
  
  if (cable.type) {
    cells.push(`<td balign="left">${cable.type}</td>`);
  }
  
  cells.push(`<td balign="left">${connectionCount}x</td>`);
  
  if (cable.gauge) {
    cells.push(`<td balign="left">${cable.gauge}</td>`);
  }
  
  if (cable.length) {
    cells.push(`<td balign="left">${cable.length}</td>`);
  }
  
  return cells.join("");
}

/**
 * Function to truncate a label to a maximum length, adding "..." if truncated
 * @param label - The original label
 * @param maxLength - Maximum allowed length (default: 30)
 * @returns The truncated label
 */
function truncateLabel(label: string, maxLength: number = 30): string {
  if (!label || label.length <= maxLength) {
    return label;
  }
  
  // Keep maxLength - 3 characters and add "..."
  return label.substring(0, maxLength - 3) + '...';
}

/**
 * Generates Graphviz nodes for all nets  
 */
function generateCableNetRows(cable: Cable): string {
  try {
    return cable.nets
      .map((net, index) => {
        if (!net.pins || !Array.isArray(net.pins)) {
          throw new DiagramError(`Invalid pins array in net for cable ${cable.name}`);
        }
        
        // Split pins into left and right side
        const leftPins = net.pins.filter(pin => pin.side === "w");
        const rightPins = net.pins.filter(pin => pin.side === "e");
        
        // Create left and right side pin labels, but truncate if too long
        const leftLabels = leftPins
          .map((pin) => {
            if (!pin.owner || pin.number === undefined) {
              throw new DiagramError(`Invalid pin in cable ${cable.name}`);
            }
            return `${pin.owner}:${pin.number}${pin.name ? ':' + pin.name : ''}`;
          })
          .join(", ");
        
        const rightLabels = rightPins
          .map((pin) => {
            if (!pin.owner || pin.number === undefined) {
              throw new DiagramError(`Invalid pin in cable ${cable.name}`);
            }
            return `${pin.owner}:${pin.number}${pin.name ? ':' + pin.name : ''}`;
          })
          .join(", ");
        
        // Truncate the labels if they're too long
        const truncatedLeftLabels = truncateLabel(leftLabels);
        const truncatedRightLabels = truncateLabel(rightLabels);
        
        // Center text shows cable number for regular nets, and "[shield]" for shield nets
        const centerText = net.isShield ? 
          "&nbsp;[shield]&nbsp;" : 
          `<b>${index + 1}</b>`;
        
        // Add spacing before shield connections
        const spacerRow = net.isShield ? 
          `<tr><td colspan="3" cellpadding="0" height="10">&nbsp;</td></tr>` : '';

        // First row: text row with connections displayed
        const textRow = `
          <tr>
            <td align="left">&nbsp;&nbsp;&nbsp;${truncatedLeftLabels}</td>
            <td align="center">${centerText}</td>
            <td align="right">${truncatedRightLabels}&nbsp;&nbsp;&nbsp;</td>
          </tr>
        `;

        // Generate wire visualization based on whether it's a shield net or regular net
        let wireViz;
        
        if (net.isShield) {
          // Shield nets have a single black line
          // Adding width="100%" to match the regular nets
          wireViz = `<tr><td cellpadding="0" height="1" bgcolor="#000000" border="0" width="100%"></td></tr>`;
        } else {
          // Regular nets have a multi-layer pattern
          const wireColor = net.color || "#000000";
          const stripedColor = net.striped || wireColor;
          
          wireViz = `
            <tr><td cellpadding="0" height="2" bgcolor="#000000" border="0" width="100%"></td></tr>
            <tr><td cellpadding="0" height="2" bgcolor="${wireColor}" border="0" width="100%"></td></tr>
            <tr><td cellpadding="0" height="2" bgcolor="${stripedColor}" border="0" width="100%"></td></tr>
            <tr><td cellpadding="0" height="2" bgcolor="#000000" border="0" width="100%"></td></tr>
          `;
        }

        // Second row: wire representation with port positioning preserved but width attributes added
        // for visual continuity
        const wireRow = `
          <tr>
            <td border="0" cellspacing="0" cellpadding="0" port="w${index + 1}w" height="${net.isShield ? 2 : 8}">
              <table cellspacing="0" cellborder="0" border="0" width="100%">
                ${wireViz}
              </table>
            </td>
            <td border="0" cellspacing="0" cellpadding="0" port="w${index + 1}" height="${net.isShield ? 2 : 8}">
              <table cellspacing="0" cellborder="0" border="0" width="100%">
                ${wireViz}
              </table>
            </td>
            <td border="0" cellspacing="0" cellpadding="0" port="w${index + 1}e" height="${net.isShield ? 2 : 8}">
              <table cellspacing="0" cellborder="0" border="0" width="100%">
                ${wireViz}
              </table>
            </td>
          </tr>
        `;

        return spacerRow + textRow + wireRow;
      })
      .join("");
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to generate net rows for cable '${cable?.name || "unknown"}': ${error.message}`);
    }
  }
}

/**
 * Generates additional items rows for connectors or cables
 */
function generateAdditionalsRows(
  additionals: Array<{ quantity?: number | string; item?: string; mpn?: string }> | undefined,
): string {
  if (!additionals || additionals.length === 0) {
    return '';
  }
  
  return `
    <tr><td colspan="1" align="center"><b>Additional</b></td></tr>
    ${additionals.map(additional => `
      <tr>
        <td colspan="1" align="center">
          ${additional.quantity ? `${additional.quantity}x ` : ''}${additional.item || ''}${additional.mpn ? ` (${additional.mpn})` : ''}
        </td>
      </tr>
    `).join("")}
  `;
}

/**
 * Generates image row for connectors or cables
 */
function generateImageRow(image: {src?: string, caption?: string} | undefined): string {
  if (!image || !image.src) {
    return '';
  }
  
  try {
    // Graphviz requires absolute file paths for images
    // We need to normalize the path and ensure it's compatible with Graphviz
    const normalizedPath = image.src.replace(/\\/g, '/');
    
    // Check if file exists
    if (!fs.existsSync(normalizedPath)) {
      console.warn(`Warning: Image file not found: ${normalizedPath}`);
    }
    
    // Graphviz has specific requirements for image inclusion in HTML-like labels
    // We need to use 'IMG' tag specifically for DOT format
    const imageHtml = `
      <tr>
        <td colspan="1" align="center" border="1" cellpadding="3">
          <table border="0" cellborder="0" cellpadding="0">
            <tr>
              <td><IMG SRC="${normalizedPath}"/></td>
            </tr>
            <tr>
              <td colspan="1" align="center" border="0" cellpadding="3">
                ${image.caption || ''}
              </td>
            </tr>
          </table>
        </td>
      </tr>
    `;

    return imageHtml;
  } catch (error) {
    // Just log a warning and return empty string rather than failing the entire diagram
    console.warn(`Warning: Failed to process image: ${error.message}`);
    return '';
  }
}

/**
 * Generates note row for connectors or cables
 */
function generateNoteRow(note: string | undefined): string {
  if (!note || note === '') {
    return '';
  }
  
  return `
    <tr>
      <td colspan="1" align="center" border="1" cellpadding="3">
        ${note}
      </td>
    </tr>
  `;
}

/**
 * Generates edges between connectors and cables
 */
function generateEdges(cables: Cable[], connectors: Connector[]): string {
  try {
    if (!cables || !Array.isArray(cables)) {
      throw new DiagramError("Invalid cables array");
    }
    
    if (!connectors || !Array.isArray(connectors)) {
      throw new DiagramError("Invalid connectors array");
    }
    
    return cables
      .flatMap((cable) => {
        if (!cable.nets || !Array.isArray(cable.nets)) {
          throw new DiagramError(`Invalid nets array for cable ${cable.name}`);
        }
        
        return cable.nets.flatMap((net, netIndex) => {
          // Set edge color and style based on whether it's a shield or not
          const edgeColor = net.isShield 
            ? "#000000" // Simple black line for shields
            : `#000000:${net.color || "#000000"}:${net.striped || net.color || "#000000"}:#000000`;
          
          const edgeStyle = net.isShield ? "dashed" : "bold";

          if (!net.pins || !Array.isArray(net.pins)) {
            throw new DiagramError(`Invalid pins array in net for cable ${cable.name}`);
          }

          return net.pins.flatMap((pin) => {
            if (!pin.owner) {
              throw new DiagramError(`Pin missing owner in cable ${cable.name}`);
            }
            
            if (pin.number === undefined) {
              throw new DiagramError(`Pin missing number in cable ${cable.name}`);
            }
            
            const sourceConnector = connectors.find((c) => c.name === pin.owner);
            if (!sourceConnector) {
              throw new DiagramError(`Referenced connector '${pin.owner}' not found for cable ${cable.name}`);
            }
            
            const sourcePort = `p${pin.number}`;
            // Use the pin's side property (should be either "w" or "e")
            const side = pin.side || "w"; // Default to west/left if not specified
            
            // Which port to connect to based on side
            const portSuffix = side === "w" ? "w" : "e";
            const targetPort = `w${netIndex + 1}${portSuffix}`;
            
            // Generate edge in BOTH directions
            return [
              `edge [fontname=arial style=${edgeStyle} color="${edgeColor}"]
              ${sourceConnector.name}:${sourcePort} -- ${cable.name}:${targetPort}`,
              
              `edge [fontname=arial style=${edgeStyle} color="${edgeColor}"]
              ${cable.name}:${targetPort} -- ${sourceConnector.name}:${sourcePort}`
            ];
          });
        });
      })
      .flat()
      .join("\n");
  } catch (error) {
    if (error instanceof DiagramError) {
      throw error;
    } else {
      throw new DiagramError(`Failed to generate edges: ${error.message}`);
    }
  }
}